---
substitutions:
  devicename: 'esp32higrow45' 
  # Esp32HiGrow45
  device_description: 'Зовнішній переносний датчик для догляду за рослинами'
  project_version: '0.1'
  update_interval: 30min
  loglevel: DEBUG
  moisture_min: '2.82'
  moisture_max: '1.39'
  conductivity_min: '0.075'
  conductivity_max: '0.25'
  # Uncomment run_duration and sleep_duration if you want to use deepsleep
  # set how long to stay awake - NOT less then 10sec
  run_duration: 10min
  # set how long to sleep in minutes
  sleep_duration: 50min

esphome:
  name: '${devicename}'
  comment: '${device_description}'
  on_boot:
    priority: 240
    then:
      - wait_until:
          condition:
            wifi.connected:
          timeout: 10s
  on_shutdown:
    then:
      - switch.turn_off: spower

#dashboard_import:
#  package_import_url: github://bruvv/LILYGO-T-Higrow-Esphome/LILYGO-T-Higrow-ESP32.yaml@main

esp32:
  board: lolin_d32

#improv_serial:

wifi:
  # Use improv (after installing either go to web.esphome.io or use the installer here: https://bruvv.github.io/LILYGO-T-Higrow-Esphome)
  # ssid: !secret wifi_ssid
  # password: !secret wifi_password
  ssid: "KAZKA_2" 
  # "AA5A76"
  password: ""
  fast_connect: True

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: '${devicename}'
#    ssid: "Esp32HiGrow45"
#    password: "Function32"
#  manual_ip:
#    static_ip: 192.168.84.45
#    gateway: 192.168.84.1
#    subnet: 255.255.255.0  

    
#captive_portal:

# Web server disabled because it was using to much ram
web_server:
 port: 80

# Enable logging
logger:
  level: '${loglevel}'

api:
  password: "Function32"

#ota:
#  safe_mode: true
#  reboot_timeout: 10min
#  num_attempts: 5

time:
  - platform: sntp
    id: esptime
    timezone: "Europe/Kiev"
    on_time_sync:
      then:
        - logger.log: "Synchronized sntp clock"
        - text_sensor.template.publish:
            id: ora_text_sync
            state: "Sync SNTP clock"
    on_time:
      #Deep sleep at 5pm and wake up at 8am.
      - hours: 17
        then:
          - delay: 1s
          #Rest up
          - deep_sleep.enter:
              id: deep_sleep_control
              until: "08:00:00"
              time_id: esptime
   
button:
  - platform: restart
    name: 'Restart - ${devicename}'

i2c:
  sda: 25
  scl: 26
  scan: true
  id: i2c_bus45
  setup_priority: -200

switch:
  # Power Switch
  - platform: gpio
    name: '${devicename} Sensor Power switch'
    pin:
      number: 4
      mode: INPUT_PULLUP
    id: spower
    restore_mode: ALWAYS_ON
    internal: true
    setup_priority: 1000

sensor:
  # Wifi sensor
  - platform: wifi_signal
    name: '${devicename} - WiFi Signal'
    update_interval: $update_interval
    id: '${devicename}_wifi_signal'
    icon: mdi:wifi-strength-1
  # Время в онлайне
  - platform: uptime
    name: ${devicename}_uptime
    
packages:
  text_sensors: !include common/text_sensors.yaml
  dht: !include common/dht.yaml
  plantsensors: !include common/plantsensors.yaml
  #waterpump: !include common/waterpump.yaml
  # bluetooth: !include common/bluetooth.yaml
  # Battery only works for 12 hours with deepsleep!
  # bme280: !include common/bme280.yaml
  deepsleep: !include common/deepsleep.yaml
  battery: !include common/battery.yaml